main: me.joshua.peso.PesoPlugin
name: Pesos
author: Joshua
version: 6.2
description: adds pesos
api-version: 1.16
commands:
   peso:
      aliases:
      - eco
      description: /help pesos for commands. Also home of admin commands
   withdraw:
      aliases:
      - w
      - take
      description: get money in item form
   deposit:
      aliases:
      - d
      - put
      description: turn item money into money
   balance:
      aliases:
      - bal
      - b
      description: check how much money you have